import json
from datetime import datetime
import yfinance as yf

today = datetime.now()


def get_market(symbol):
    try:
        ticker = yf.Ticker(symbol)
        hist = ticker.history(period="2d")

        if len(hist) < 2:
            return None

        last = float(hist["Close"].iloc[-1])
        prev = float(hist["Close"].iloc[-2])

        return {
            "price": round(last, 2),
            "change": round(last - prev, 2)
        }

    except Exception:
        return None


# ------------------------
# Financial Markets
# ------------------------

financial_symbols = {
    "S&P 500": "^GSPC",
    "Dow Jones": "^DJI",
    "NASDAQ": "^IXIC",
    "US Dollar Index": "DX-Y.NYB",
    "Crude Oil": "CL=F"
}

financial = []

for name, symbol in financial_symbols.items():

    market = get_market(symbol)

    if market:
        financial.append({
            "market": name,
            "value": market["price"],
            "change": market["change"]
        })


# ------------------------
# Wheat Futures
# ------------------------

wheat_symbols = {
    "Chicago Wheat": "ZW=F",
    "Kansas City Wheat": "KE=F"
}

wheat = []

for name, symbol in wheat_symbols.items():

    market = get_market(symbol)

    if market:
        wheat.append({
            "market": name,
            "price": market["price"],
            "change": market["change"]
        })


# ------------------------
# Website Data
# ------------------------

data = {

    "date": today.strftime("%A, %B %d, %Y"),

    "updated": today.strftime("%I:%M %p"),

    "marketMood": "Loading",

    "coffeeReport":
    "Automatic market report generated by GitHub Actions.",

    "wheat": wheat,

    "crops": [],

    "livestock": [],

    "financial": financial,

    "weather": {
        "location": "Washington",
        "temp": "--",
        "conditions": "Loading"
    }

}

with open("market-data.json", "w") as f:
    json.dump(data, f, indent=4)

print("market-data.json updated.")
